name: Update README with Current Issues

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Get current milestone
        id: milestone
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          MILESTONE_TITLE=$(gh api graphql -f query='
            query($owner: String!, $repo: String!) {
              repository(owner: $owner, name: $repo) {
                milestones(states: OPEN, first: 1, orderBy: {field: DUE_DATE, direction: ASC}) {
                  nodes { title }
                }
              }
            }' -f owner='${{ github.repository_owner }}' -f repo='${{ github.event.repository.name }}' | jq -r '.data.repository.milestones.nodes[0].title')
          echo "title=$MILESTONE_TITLE" >> $GITHUB_OUTPUT

      - name: Fetch and format issues
        id: issues
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Haal de issues op en formatteer ze als Markdown tabelrijen
          ISSUES_LIST=$(gh issue list --state open --milestone "${{ steps.milestone.outputs.title }}" --limit 5 --json title,url --template '{{range .}}| [{{.title}}]({{.url}}) |{{printf "\n"}}{{end}}')
          # Maak een multiline string voor de vervanging in de volgende stap
          echo "markdown_table<<EOF" >> $GITHUB_OUTPUT
          echo "$ISSUES_LIST" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update README file
        run: |
          # Lees de README, vervang de content tussen de markers, en schrijf terug
          # Dit is een robuustere methode
          python3 -c "import re; f=open('README.md','r+'); content=f.read(); result=re.sub(r'.*', '\n${{ steps.issues.outputs.markdown_table }}', content, flags=re.DOTALL); f.seek(0); f.truncate(); f.write(result)"

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "docs: update milestone issues in README" && git push)